# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Why On Mars?
email: your-email@example.com
description:  # this means to ignore newlines until "baseurl:"
  "really, why?"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
logo: /images/logo1.5.png
masthead title: "really, why?"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal-mistakes-skin: "neon"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

#outputting
paginate: 5 # amount of posts to show
paginate_path: /page:num/

#defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

#fonts
google fonts:
  - name: "Francois One"
    weights: "400,400i,700,700i"
  - name: "Open Sans"
    weights: "400,400i,700,700i"
  - name: "Alegreya"
    weights: "400,400i,700,700i"
  - name: "Montaga" #a serif font
    weights: "400,400i,700,700i"


#footer
footer:
  links:
      - label: "Twitter"
        icon: "fab fa-fw fa-twitter-square"
        url: "https://twitter.com/mars_why"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/whyonmars"

#for social sharing
twitter:
  username: "mars_why"

#about author


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
